### Check if possible to start a new battle
GET http://localhost:8080/api/campaign/1/battle/check-availability
Authorization: Bearer {{BEARER_TOKEN}}
Accept: application/json
Content-Type: application/json

### Check if there is an ongoing battle for today
GET http://localhost:8080/api/campaign/1/battle/check-ongoing
Authorization: Bearer {{BEARER_TOKEN}}
Accept: application/json
Content-Type: application/json

### Get battle for today
GET http://localhost:8080/api/campaign/1/battle/ongoing
Authorization: Bearer {{BEARER_TOKEN}}
Accept: application/json
Content-Type: application/json

### Get finished for today
GET http://localhost:8080/api/campaign/1/battle/finished
Authorization: Bearer {{BEARER_TOKEN}}
Accept: application/json
Content-Type: application/json

### Start a new battle
POST http://localhost:8080/api/campaign/1/battle/new
Authorization: Bearer {{BEARER_TOKEN}}
Accept: application/json
Content-Type: application/json

### Triggers NPC's turn in a battle
POST http://localhost:8080/api/campaign/1/battle/action/trigger-npc-turn
Authorization: Bearer {{BEARER_TOKEN}}
Accept: application/json
Content-Type: application/json



### Char ID 3 (Hero for seeded data) attack physically Char ID 1
POST http://localhost:8080/api/campaign/1/battle/1/action/attack
Authorization: Bearer {{BEARER_TOKEN}}
Accept: application/json
Content-Type: application/json

{
  "performingCharacterId": 3,
  "targetCharacterId": 1,
  "action": "PHYSICAL_ATTACK"
}

### Char ID 3 (Hero for seeded data) casts a consumable on  Char ID 3
POST http://localhost:8080/api/campaign/1/battle/1/action/consumable
Authorization: Bearer {{BEARER_TOKEN}}
Accept: application/json
Content-Type: application/json

{
  "performingCharacterId": 3,
  "targetCharacterId": 3,
  "action": "CONSUMABLE",
  "cardToUseId": 2
}

### Char ID 3 (Hero for seeded data) casts a spell on  Char ID 1
POST http://localhost:8080/api/campaign/1/battle/1/action/spell
Authorization: Bearer {{BEARER_TOKEN}}
Accept: application/json
Content-Type: application/json

{
  "performingCharacterId": 3,
  "targetCharacterId": 1,
  "action": "SPELL",
  "cardToUseId": 1
}